### ISSUE TITLE
Editor errors and black screen bug

### ISSUE THREAD

**Issue by EmeraldEelEntertainment** [keijiro/Retro3DPipeline#2] opened 2018-07-13 18:57 UTC
I imported this rendering pipeline to a new project and it doesn't work. I get many errors and the Scene window has a weird black filter over it, obscuring some helpful editor GUIs. I'm using the current stable build of Unity 2018.

**Comment by keijiro** [comment] 2018-08-06 03:22
Actually I'm not sure what the root cause is, this might be related to the temporary RT format issue (#1), which is fixed in the latest updates.

**Comment by keijiro** [comment] 2018-08-06 03:23
I'm closing this ticket. Please feel free to reopen if it sill reproduces.

**Closed as completed by keijiro** 2018-08-06 03:23 UTC
Labels: question
